name: CI

on:
  push:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        version: ["18.04", "20.04", "22.04", "24.04"]
        architecture: ["x86_64", "arm64"]
        exclude:
          - architecture: ${{ github.event_name == 'push' && 'arm64' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{matrix.version}} - ${{matrix.architecture}}
