name: CI

on:
  push:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@setup-homebrew-improvements
      - run: brew readall
        if: always()
      - run: brew audit
        if: always()
      - run: brew doctor
        if: always()
      - run: brew install hello
        if: always()
