name: CI

on:
  push:

env:
  GNUPGHOME: /tmp/gnupghome

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
      options: --user=linuxbrew
    steps:
      - run: |
          set -euo pipefail

          mkdir -p "$GNUPGHOME"
          chmod 0700 "$GNUPGHOME"

          GPG_EXEC=$(command -v gpg)
          if [ -z "$GPG_EXEC" ]; then
            echo "GPG not found." >&2
            exit 1
          fi

          GPG_VERSION=$(gpg --version | head -n1 | cut -d' ' -f3)
          echo $GPG_VERSION
          echo `$GPG_EXEC --version`
          GPG_MAJOR=$(echo $GPG_VERSION | cut -d. -f1)
          GPG_MINOR=$(echo $GPG_VERSION | cut -d. -f2)
          echo $GPG_MAJOR
          if (( GPG_MAJOR > 2 || (GPG_MAJOR == 2 && GPG_MINOR >= 1) )); then
            PINENTRY_MODE="--pinentry-mode loopback"
          else
            PINENTRY_MODE=""
          fi

          # Wrapper script to use passphrase non-interactively with git
          GPG_WITH_PASSPHRASE=$(mktemp)
          echo "$GPG_EXEC"' '"$PINENTRY_MODE"' --passphrase "$HOMEBREW_GPG_PASSPHRASE" --batch --no-tty "$@"' > $GPG_WITH_PASSPHRASE
          chmod +x $GPG_WITH_PASSPHRASE
          $GPG_WITH_PASSPHRASE test
