name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu18.04:latest
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu20.04:latest
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:latest
            repo: homebrew-core
          - os: ubuntu-20.04
            repo: homebrew-core
          - os: ubuntu-22.04
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu18.04:latest
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu20.04:latest
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:latest
            repo: homebrew-cask
          - os: ubuntu-20.04
            repo: homebrew-cask
    steps:
      - run: |
          cd /tmp
          GIT_TRACE2=/tmp/test.log GIT_TRACE=2 GIT_CURL_VERBOSE=2 GIT_TRACE_PERFORMANCE=2 GIT_TRACE_PACK_ACCESS=2 GIT_TRACE_PACKET=2 GIT_TRACE_SETUP=2 GIT_TRACE_SHALLOW=2 \
          git -c remote.origin.promisor=true clone https://github.com/Homebrew/${{ matrix.repo }}
      - if: always()
        run: cat /tmp/test.log
