name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: action/checkout@v4
        with:
          persist-credentials: false
    
      - uses: ./.github/workflows
        with:
          bottle-directory: tpm
