name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - run:
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          brew tap homebrew/bundle
