name: CI

on:
  push:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          stable: true

      - run: brew --version

      - run: git -C "$(brew --repo)" tag --list --sort="-version:refname"
