name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew test-bot --only-cleanup-before --tap=homebrew/core
      - run: brew test-bot --only-setup --tap=homebrew/core
      - run: brew test-bot --only-tap-syntax --tap=homebrew/core
      - run: |
          mkdir bottles
          cd bottles
          sed -i 's/def install/def install\n  ENV.append_to_cflags "-DQELFPARSER_DEBUG"/g'
          brew test-bot --only-formulae --tap=homebrew/core qt
      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: bottles
