name: CI

on:
  push:

jobs:
  tests:
    strategy:
      matrix:
        test: [1,2,3]
        include:
          - os: ubuntu-latest
            target: a
          - os: windows-latest
            target: b
          - os: macos-latest
            target: c
    runs-on: ${{matrix.os}}
    steps:
      - run: |
          echo ${{matrix.target}} - ${{matrix.test}}
