name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{matrix.os == 'ubuntu-latest' && fromJson('{"image":"homebrew/brew","options":"--user=linuxbrew"}') || ""}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - run: |
          echo $GITHUB_WORKSPACE
          echo "${{ github.workspace }}"
          echo "${{ matrix.os }}-${{ matrix.container }}"
