name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TEST_DIR }}
    steps:
      - run: |
          echo "'$PWD'"
          echo "'$TEST_DIR'"
          echo "TEST_DIR=/tmp" >> "$GITHUB_ENV"
      - run: |
          echo "'$PWD'"
          echo "'$TEST_DIR'"
  
  tests2:
    name: Tests 2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ steps.teststep.outputs.outdir }}
    steps:
      - id: teststep
        run: |
          echo "'$PWD'"
          echo "'${{ steps.teststep.outputs.outdir }}'"
          echo "outdir=/tmp" >> "$GITHUB_OUTPUT"
      - run: |
          echo "'$PWD'"
          echo "'${{ steps.teststep.outputs.outdir }}'"
