name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - env:
          TESTENV: ${{ secrets.ABC && 'abc' }}
          TESTENV2: ${{ github.token && 'abc2' }}
          TESTENV3: ${{ secrets.ABC }}
        run: |
          echo $TESTENV
          echo $TESTENV2
          if [[ -n "$TESTENV" ]]
          then
            echo "1"
          fi
          if [[ -n "$TESTENV2" ]]
          then
            echo "2"
          fi
          ruby -e 'p ENV["TESTENV"]'
          ruby -e 'p ENV["TESTENV2"]'
          ruby -e 'p ENV["TESTENV3"]'
