name: CI

on:
  push:

jobs:
  tests:
    runs-on: macos-13
    steps:
      - run: |
          cat <foo.c <<EOS
          #include <curl/multi.h>
          
          int main() {
            CURLM *m = curl_multi_init();
            curl_multi_get_handles(m);
            return 0;
          }
          EOS
          /usr/bin/clang -mmacos-version-min=13 -lcurl foo.c
          ./a.out
