name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:master
          - os: ubuntu-22.04
    steps:
      - run: git config --list --show-origin

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true

      - run: git -C "$(brew --repo homebrew/core)" config --list --show-origin
          
