name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TEST_DIR }}/a
    steps:
      - run: |
          echo "'$PWD'"
          echo "'$TEST_DIR'"
          echo "TEST_DIR=/tmp" >> "$GITHUB_ENV"
      - run: |
          echo "'$PWD'"
          echo "'$TEST_DIR'"
