name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: ghcr.io/homebrew/ubuntu16.04:master
          - os: macos-latest
    steps:
      - run: |
          echo $GITHUB_WORKSPACE
          echo "${{ github.workspace }}"
          echo "${{ matrix.os }}-${{ matrix.container }}"
