name: test

on:
  push:

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: databricks/homebrew-tap
        
      - name: Configure Git
        uses: Homebrew/actions/git-user-config@master

      # This action automatically installs the locally checked out tap.
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        env:
          GITHUB_REPOSITORY: databricks/homebrew-tap
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CLI
        run: |
          brew install databricks

      - name: Run CLI
        run: |
          databricks version
