name: CI

on:
  push:
  pull_request:

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: always()
        with:
          github-token: ' '
          script: |
            console.log(await github.rest.activity.listStargazersForRepo({
              owner: "Homebrew",
              repo: "brew"
            }));
            console.log(await github.rest.rateLimit.get());
       
      - uses: actions/github-script@v6
        if: always()
        with:
          script: |
            console.log(await github.rest.activity.listStargazersForRepo({
              owner: "Homebrew",
              repo: "brew"
            }));
            console.log(await github.rest.rateLimit.get());

      - uses: actions/github-script@v6
        if: always()
        with:
          github-token: abc
          script: |
            console.log(await github.rest.activity.listStargazersForRepo({
              owner: "Homebrew",
              repo: "brew"
            }));
            console.log(await github.rest.rateLimit.get());
