name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::warning test"
          echo "::warning::test"
          echo "::error test"
          echo "::error::test"
