name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu18.04:latest
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu20.04:latest
            repo: homebrew-core
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:latest
            repo: homebrew-core
          - os: ubuntu-20.04
            repo: homebrew-core
          - os: ubuntu-22.04
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu18.04:latest
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu20.04:latest
            repo: homebrew-cask
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:latest
            repo: homebrew-cask
          - os: ubuntu-20.04
            repo: homebrew-cask
    steps:
      - run: |
          git clone https://github.com/Homebrew/${{ matrix.repo }}
