name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            container: ghcr.io/homebrew/ubuntu22.04:master
          - os: ubuntu-24.04
            container: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew install ola
      - run: ola_plugin_state -h
      - run: brew uninstall ola && brew install -s ola
      - run: ola_plugin_state -h
