name: CI

on:
  push:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: sudo chmod -R g-w,o-w /home/linuxbrew $HOME /opt
      - run: sudo rm -rf /usr/share/fonts/cmap
