name: CI

on:
  push:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PATH
          ls -la /opt
      - run: sudo chmod -R g-w,o-w /home/linuxbrew
      - run: sudo chmod -R g-w,o-w $HOME
      - run: sudo chmod -R g-w,o-w /opt
      - run: sudo rm -rf /usr/share/fonts/cmap
      - run: brew doctor
