name: CI

on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
    steps:
      - run: |
          ls -l /usr/local/lib
          ls -l /usr/local/lib/node_modules
          ls -l /usr/local/lib/node_modules/npm
          ls -l /usr/local/lib/node_modules/npm/docs
          ls -l /usr/local/lib/node_modules/npm/docs/content
          ls -l /usr/local/lib/node_modules/npm/docs/content/commands
