name: CI

on:
  push:

jobs:
  tests:
    name: Rust test
    runs-on: ubuntu-latest
    container: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - shell: bash --noprofile --norc -o pipefail {0}
        run: |
          for pkg in $(brew uses --eval-all --include-build --formula rust)
          do
            brew install -q ${pkg}
            brew uninstall ${pkg}
          done
