name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      volumes:
        - /mnt:/mnt
    steps:
      - run: |
          df -h
