name: CI

on:
  push:

jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: ghcr.io/homebrew/ubuntu22.04:master
          - os: ubuntu-latest
    steps:
      - run: |
          df -h
