name: CI

on:
  push:

jobs:
  tests:
    runs-on: macos-15
    steps:
      - run: op --version || echo "Not installed"

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
        with:
          version: latest-beta

      - run: op --version
