name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      options: --user=linuxbrew
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: |
          brew install --verbose --build-bottle ca-certificates
          ls -l /home/linuxbrew/.linuxbrew/Cellar/ca-certificates/2023-08-22
          ls -l /home/linuxbrew/.linuxbrew/Cellar/ca-certificates/2023-08-22/share/ca-certificates
          brew bottle --verbose --json ca-certificates --keep-old --only-json-tab
