name: CI

on:
  push:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ${GITHUB_WORKSPACE}
          echo test > test.txt
          rm README.md
          git add test.txt README.md
    
      - uses: Homebrew/actions/api-commit-and-push@api-commit-and-push
        with:
          message: "Test commit"
          branch: test29
          token: ${{ github.token }}
