name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      volumes:
        - /mntz:/mntz
    steps:
      - run: |
          df -h
          ls -la /mnt
          cat /mnt/DATALOSS_WARNING_README.txt
