name: CI

on:
  workflow_dispatch:
    inputs:
      test:
        description: "test"
        type: boolean
        required: false
        default: false

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      volumes:
        - /mnt:/mnt
    steps:
      - run: |
          df -h
          ls -la /mnt
          echo "z${INPUT_TEST}z"
          echo "z${INPUTS_TEST}z"
          echo "z${{ inputs.test }}z"
