name: test
on:
  push:

defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  test:
    runs-on: "macos-12"

    steps:
      - run: |
          brew unlink python@3.10
          brew install --force --overwrite sidekickmoney/homebrew-skm/python@3.10
