name: CI

on:
  push:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: teststep
        run: |
           printf "::set-output name=test1::test\ntest2\n"
           printf "::set-output name=test2::test%0Atest2\n"
           printf "::set-output name=test3::100%.\n"
           printf "::set-output name=test4::100%25\n"
           printf "test5=test\ntest2\n" >> $GITHUB_OUTPUT
           printf "test6=test%0Atest2\n" >> $GITHUB_OUTPUT
           printf "test7=100%.\n" >> $GITHUB_OUTPUT
           printf "test8=100%25\n" >> $GITHUB_OUTPUT
           printf "test9=a=b\n" >> $GITHUB_OUTPUT
      - run: |
          echo "test1=${{steps.teststep.outputs.test1}}"
          echo "test2=${{steps.teststep.outputs.test2}}"
          echo "test3=${{steps.teststep.outputs.test3}}"
          echo "test4=${{steps.teststep.outputs.test4}}"
          echo "test5=${{steps.teststep.outputs.test5}}"
          echo "test6=${{steps.teststep.outputs.test6}}"
          echo "test7=${{steps.teststep.outputs.test7}}"
          echo "test8=${{steps.teststep.outputs.test8}}"
          echo "test9=${{steps.teststep.outputs.test9}}"
