name: CI

on:
  push:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      options: --data-root=/mnt
    steps:
      - run: |
          df -h
